// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import 	"github.com/coze-dev/coze-studio/backend/api/model/crossdomain/plugin"


const TableNamePluginProductRef = "plugin_product_ref"

// PluginProductRef Plugin Product Reference
type PluginProductRef struct {
	ID           int64                  `gorm:"column:id;primaryKey;comment:Plugin ID" json:"id"`                                                      // Plugin ID
	SpaceID      int64                  `gorm:"column:space_id;not null;comment:Space ID" json:"space_id"`                                             // Space ID
	DeveloperID  int64                  `gorm:"column:developer_id;not null;comment:Developer ID" json:"developer_id"`                                 // Developer ID
	RefProductID int64                  `gorm:"column:ref_product_id;not null;comment:Referent Product ID" json:"ref_product_id"`                      // Referent Product ID
	IconURI      string                 `gorm:"column:icon_uri;not null;comment:Icon URI" json:"icon_uri"`                                             // Icon URI
	ServerURL    string                 `gorm:"column:server_url;not null;comment:Server URL" json:"server_url"`                                       // Server URL
	PluginType   int32                  `gorm:"column:plugin_type;not null;comment:Plugin Type, 1:http, 6:local" json:"plugin_type"`                   // Plugin Type, 1:http, 6:local
	CreatedAt    int64                  `gorm:"column:created_at;not null;autoCreateTime:milli;comment:Create Time in Milliseconds" json:"created_at"` // Create Time in Milliseconds
	Version      string                 `gorm:"column:version;not null;comment:Plugin Version, e.g. v1.0.0" json:"version"`                            // Plugin Version, e.g. v1.0.0
	VersionDesc  string                 `gorm:"column:version_desc;comment:Plugin Version Description" json:"version_desc"`                            // Plugin Version Description
	Manifest     *plugin.PluginManifest `gorm:"column:manifest;comment:Plugin Manifest;serializer:json" json:"manifest"`                               // Plugin Manifest
	OpenapiDoc   *plugin.Openapi3T      `gorm:"column:openapi_doc;comment:OpenAPI Document, only stores the root;serializer:json" json:"openapi_doc"`  // OpenAPI Document, only stores the root
}

// TableName PluginProductRef's table name
func (*PluginProductRef) TableName() string {
	return TableNamePluginProductRef
}
